### ISSUE TITLE
In react app, how to get the value of global editor?

### ISSUE THREAD

**Issue by nguyenngoclongdev** [nocode-js/sequential-workflow-editor#25]
In react app, how to get the value of global editor?
I try to use hook useGlobalEditor, but throw exception.

```
react_devtools_backend_compact.js:12966 React Router caught the following error during render Error: Cannot find global editor context
    at useGlobalEditor (index.js:75:11)
    at WorkflowEditor (WorkflowEditor.tsx:54:106)
    at fm (react-dom.development.js:1:152112)
    at react-dom.development.js:1:196268
    at Hg (react-dom.development.js:1:197617)
    at qw (react-dom.development.js:1:244731)
    at Lw (react-dom.development.js:1:237660)
    at _w (react-dom.development.js:1:237542)
    at Nw (react-dom.development.js:1:237304)
    at mw (react-dom.development.js:1:234875) 
```

**Comment by b4rtaz** [comment]
Hello @nguyenngoclongdev! You can use `useGlobalEditor` only inside the editor. To read a value from the editor outside you should read your definition.

**Comment by b4rtaz** [comment]
You cannot use the `useGlobalEditor()` hook with the sequential workflow editor, because it doesn't use React hooks.

To read values provided by the root editor you should read the root properties of your definition (`Definition { properties: ... }`).
